version: '3'
services:
  web:
    container_name: examplerapp
    restart: always
    build: .
    ports: 
       - "5000:3000"
    links:
       - mongo
    volumes:
       - .:/usr/src/app
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports: 
       - "27017:27017"
    
